### ISSUE TITLE
Task branches missing

### ISSUE THREAD

**Issue by psychas** [DigitalCareerInstitute/spa_todolist#1]
I have counted many task branches missing. 
Maybe you have multiple stage-branches that resolve one task-branch. That's why the numbering doesn't really add up. 
If you haven't pushed the missing task-branches please do, so we can have a task-branch for each stage-branch. 
If you are following some different kind of pattern, please document it somewhere so the teacher using the repos will know what to look for.

**Comment by foobaroo** [comment]
The numbering does not add up because not each stage is followed by a task. That is okay.

**Comment by psychas** [comment]
Itamar's instructions were saying one stage for each task i think. Please check again.
https://github.com/DigitalCareerInstitute/web-development-materials/issues/14
