### ISSUE TITLE
tasks.md and changelog.md update

### ISSUE THREAD

**Issue by psychas** [DigitalCareerInstitute/spa_todolist#3]
It would be nice for those two files to have a history of all the changes made in each stage.
So instead of removing the old tasks/changes in each branch, just sum them up, newest on top, just like this: 
https://github.com/DigitalCareerInstitute/robo-shop-workshops/blob/stage/03-handlebars-templates/TASKS.md
https://github.com/DigitalCareerInstitute/robo-shop-workshops/blob/stage/03-handlebars-templates/CHANGELOG.md

**Comment by foobaroo** [comment]
Okay.

**Comment by psychas** [comment]
I think that you should do it for the TASKS.md as well.
