### ISSUE TITLE
Server Code

### ISSUE THREAD

**Issue by psychas** [DigitalCareerInstitute/spa_todolist#8]
I believe the repos was only about react but i see you made a little server, i guess to test your react-app. There is this alternative https://jsonplaceholder.typicode.com/.
It's an open API for todos. You can post, delete, put, get so it will be fine with your react-app.
Please remove the server code and use the alternative instead.

**Comment by foobaroo** [comment]
Nope. The server stays.

**Comment by psychas** [comment]
Please check with Itamar cause the students are learning how to build a server on the Data Server module which runs parallel with this.
